CREATE TABLE IF NOT EXISTS etudiants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(100) UNIQUE NOT NULL,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    matricule VARCHAR(100),
    photo_path VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS presences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(100) NOT NULL,
    entree DATETIME,
    sortie DATETIME,
    status VARCHAR(50),
    FOREIGN KEY (uid) REFERENCES etudiants(uid) ON DELETE CASCADE ON UPDATE CASCADE
);
